import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { 
  Dumbbell, 
  Brain, 
  Target, 
  TrendingUp, 
  Users, 
  Star,
  ArrowRight,
  CheckCircle
} from 'lucide-react';

const HomePage = () => {
  const { user } = useAuth();

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Workouts',
      description: 'Get personalized workout plans generated by advanced AI based on your goals and fitness level.',
      color: 'text-blue-600'
    },
    {
      icon: Target,
      title: 'Custom Diet Plans',
      description: 'Receive tailored nutrition recommendations and meal plans to fuel your fitness journey.',
      color: 'text-emerald-600'
    },
    {
      icon: TrendingUp,
      title: 'Smart AI Coach',
      description: 'Chat with your personal AI trainer for guidance, motivation, and expert advice.',
      color: 'text-purple-600'
    },
    {
      icon: Users,
      title: 'Save Your Plans',
      description: 'Keep all your AI-generated workout and diet plans organized and accessible.',
      color: 'text-orange-600'
    }
  ];

  const benefits = [
    'Personalized workout plans for all fitness levels',
    'AI-generated meal plans and nutrition tracking',
    'Real-time form feedback and exercise guidance',
    '24/7 AI fitness coach availability',
    'Save and organize all your plans',
    'Beautiful, easy-to-follow plan layouts'
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-slate-900 via-emerald-900 to-emerald-800 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 lg:py-32">
          <div className="text-center">
            <div className="flex justify-center mb-8">
              <div className="p-4 bg-emerald-600/20 rounded-full">
                <Dumbbell className="h-16 w-16 text-emerald-400" />
              </div>
            </div>
            
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6 leading-tight">
              Your AI-Powered
              <span className="text-emerald-400 block">Fitness Journey</span>
            </h1>
            
            <p className="text-xl text-slate-300 mb-8 max-w-3xl mx-auto leading-relaxed">
              Transform your fitness routine with personalized AI coaching, custom workout plans, 
              and intelligent nutrition guidance. Start your journey to a healthier you today.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              {user ? (
                <div className="flex flex-col sm:flex-row gap-4">
                  <Link
                    to="/workout-planner"
                    className="inline-flex items-center px-8 py-4 bg-emerald-600 text-white font-semibold rounded-xl hover:bg-emerald-700 transition-all duration-200 transform hover:scale-105"
                  >
                    Create Workout Plan
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </Link>
                  <Link
                    to="/diet-planner"
                    className="inline-flex items-center px-8 py-4 border-2 border-white/20 text-white font-semibold rounded-xl hover:bg-white/10 transition-all duration-200"
                  >
                    Create Diet Plan
                  </Link>
                </div>
              ) : (
                <>
                  <Link
                    to="/register"
                    className="inline-flex items-center px-8 py-4 bg-emerald-600 text-white font-semibold rounded-xl hover:bg-emerald-700 transition-all duration-200 transform hover:scale-105"
                  >
                    Start Free Trial
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </Link>
                  <Link
                    to="/login"
                    className="inline-flex items-center px-8 py-4 border-2 border-white/20 text-white font-semibold rounded-xl hover:bg-white/10 transition-all duration-200"
                  >
                    Login
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mb-4">
              Revolutionize Your Fitness
            </h2>
            <p className="text-xl text-slate-600 max-w-3xl mx-auto">
              Experience the future of fitness with AI-powered personalization and expert guidance
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="group p-8 bg-slate-50 rounded-2xl hover:bg-white hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2"
              >
                <div className={`inline-flex p-3 rounded-xl bg-white shadow-sm mb-6 ${feature.color}`}>
                  <feature.icon className="h-8 w-8" />
                </div>
                <h3 className="text-xl font-semibold text-slate-900 mb-4">
                  {feature.title}
                </h3>
                <p className="text-slate-600 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mb-6">
                Why Choose FitAI?
              </h2>
              <p className="text-xl text-slate-600 mb-8">
                Join thousands of users who have transformed their fitness journey with our AI-powered platform.
              </p>
              
              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-start">
                    <CheckCircle className="h-6 w-6 text-emerald-600 mr-3 mt-0.5 flex-shrink-0" />
                    <span className="text-slate-700">{benefit}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="relative">
              <div className="bg-gradient-to-br from-emerald-600 to-blue-600 rounded-2xl p-8 text-white">
                <div className="text-center">
                  <Star className="h-12 w-12 text-yellow-300 mx-auto mb-4" />
                  <blockquote className="text-lg mb-6 italic">
                    "FitAI has completely transformed my workout routine. The AI coach 
                    feels like having a personal trainer available 24/7!"
                  </blockquote>
                  <cite className="font-semibold">- Sarah Johnson</cite>
                  <p className="text-emerald-200 text-sm">Lost 30 lbs in 4 months</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-slate-900 text-white">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl lg:text-4xl font-bold mb-6">
            Ready to Transform Your Fitness?
          </h2>
          <p className="text-xl text-slate-300 mb-8">
            Join thousands of users who are already achieving their fitness goals with AI-powered guidance.
          </p>
          
          {!user && (
            <Link
              to="/register"
              className="inline-flex items-center px-8 py-4 bg-emerald-600 text-white font-semibold rounded-xl hover:bg-emerald-700 transition-all duration-200 transform hover:scale-105"
            >
              Get Started Free
              <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          )}
        </div>
      </section>
    </div>
  );
};

export default HomePage;